default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: simple_wellness_development
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: simple_wellness_test

